### ISSUE TITLE
Not really an issue..

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#10]
But is there any other place such as a Discord server for feedback or discussion of this mod?

**Comment by HugoZink** [comment]
Nope. I don't have Discords or anything to discuss this mod.

If I ever do such a thing I'd want an official OK from Solo Queue Pixy (the original author) first. If you have any feedback about things that should be changed/might be neat/suggestions, feel free to open it as an issue.

**Comment by Bwamo** [comment]
Made an inquiry
![steam_2020-08-07_14-26-00](https://user-images.githubusercontent.com/23544898/89676624-f89fe800-d8b9-11ea-931d-c3103c858d5c.png)
