### ISSUE TITLE
Error initializing weapon parts.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#100]
[2021_01_27_log.txt](https://github.com/HugoZink/IreNFist/files/5882078/2021_01_27_log.txt)

Didn't played vanilla a while. Didn't found any issue with any weapon parts tho, but I still leave it here.

**Comment by HugoZink** [comment]
Seems to be related to the SCAR-L. Support for this weapon will be removed in the next update to prevent this from happening again. Thanks for your report!

**Comment by HugoZink** [comment]
Fixed.
