### ISSUE TITLE
crashing on shotgun fire + custom weapon request

### ISSUE THREAD

**Issue by Coremanite** [HugoZink/IreNFist#101]
[Triton TR15](https://modworkshop.net/mod/27651)
[Crash.txt](https://pastebin.com/NBcAsNqV)
crash is caused upon firing a shotgun at enemies.

**Comment by HugoZink** [comment]
The TR-15 is already supported.

I'll take a look at the shotgun in a bit. It shouldn't break like that.

**Comment by HugoZink** [comment]
Does the crash still happen without Pocohud installed? Poco is ancient by now, and it looks like some other mod is actually causing the crash.

**Comment by Coremanite** [comment]
> Does the crash still happen without Pocohud installed? Poco is ancient by now, and it looks like some other mod is actually causing the crash.

yes, still occurs without pocohud.
was not aware about the TR15, it isn't in the supported custom weapons list on the mod workshop mod page.

**Comment by HugoZink** [comment]
Looks like this happens if you have another mod with burstfire installed, such as vanillahud plus. I'll take a look at it.

**Comment by HugoZink** [comment]
Fixed.
