### ISSUE TITLE
Error Initializing Parts

### ISSUE THREAD

**Issue by wmafranz** [HugoZink/IreNFist#103]
Got this error popping up a lot now that I've updated my BeardLib mods. It tells me I should post my BLT Log here, so here it is:
[2021_02_27_log.txt](https://github.com/HugoZink/IreNFist/files/6055075/2021_02_27_log.txt)

**Comment by wmafranz** [comment]
![20210227131828_1](https://user-images.githubusercontent.com/25199988/109396190-67986900-78fe-11eb-9bc2-3def7c3ac8ef.jpg)

**Comment by HugoZink** [comment]
Thanks, I'll take a look at it.

**Comment by wmafranz** [comment]
Heads up, I found out what mod was causing the error. It was the Mossberg 590 mod. I uninstalled it and now the error doesn't come up anymore.

**Comment by HugoZink** [comment]
@wmafranz I was indeed aware that it was an incompatibility with the Mossberg 590. It should be fixed now in the latest build.
