### ISSUE TITLE
Missing gadget rails on secondary akimbos

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#104]
Not a big issue, but I thought I'd bring this up.

It's a bit hard to tell on the Bernetti and Sparrow screenshots since they use smaller rails.

_Bernetti w/standard frame_
![218620_20210305172632_1](https://user-images.githubusercontent.com/70559253/110188302-6c668c80-7dd8-11eb-945a-b8670c68ff6f.png)

_Sparrow 941 w/F-Model kit_
![218620_20210305172650_1](https://user-images.githubusercontent.com/70559253/110188309-7092aa00-7dd8-11eb-8737-644e6003feae.png)

_M13_
![218620_20210305172702_1](https://user-images.githubusercontent.com/70559253/110188313-74263100-7dd8-11eb-952f-afc5a0c31e99.png)

_Chimano Compact_
![218620_20210305172721_1](https://user-images.githubusercontent.com/70559253/110188316-75575e00-7dd8-11eb-8f26-22098f19c2ac.png)

**Comment by HugoZink** [comment]
Confirmed, thanks! I'll take a look.

**Comment by HugoZink** [comment]
Fixed.
