### ISSUE TITLE
"Optimal Range" statistic clips into black market descriptions

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#106]
god damn it overkill why must you ruin everything you touch

![20210320212931_1](https://user-images.githubusercontent.com/70559253/111894153-a3869180-89c5-11eb-9340-f26dc3b48803.jpg)
![20210320212938_1](https://user-images.githubusercontent.com/70559253/111894155-a5505500-89c5-11eb-8517-dfccb1dfcab4.jpg)
![20210320213803_1](https://user-images.githubusercontent.com/70559253/111894156-a71a1880-89c5-11eb-9d6b-68fe78a788b3.jpg)

**Comment by HugoZink** [comment]
I nuked the falloff changes but I guess I forgot to account for this in the UI. Thanks for the report, will fix!

**Comment by HugoZink** [comment]
Fixed.
