### ISSUE TITLE
missing stats for Sig MCX Virtus, Galil ACE 23, HK433

### ISSUE THREAD

**Issue by Coremanite** [HugoZink/IreNFist#107]
Sig MCX: https://modworkshop.net/mod/31137
Galil ACE: https://modworkshop.net/mod/19075
HK433: https://modworkshop.net/mod/30992

**Comment by HugoZink** [comment]
I'll look into adding them.

**Comment by Coremanite** [comment]
thanks
the fmg 9 is missing too

**Comment by HugoZink** [comment]
Added.
