### ISSUE TITLE
John Wick Weapon Pack DLC - Silentgear Silencer doesn't have the silencer fall-off warning.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [HugoZink/IreNFist#109]
![](https://user-images.githubusercontent.com/13170204/117536313-9a479780-affa-11eb-8549-2852fa2cf638.jpg)

No idea if it still applies despite the description text not being changed. Would especially know, since some Custom attachments suffer from the same obvious issue, and don't know if I can suggest to add support from them.

**Comment by HugoZink** [comment]
Yes, the silencer stats are still applied. It looks like it just doesn't display the description for it yet. Will fix.

Thanks for your report!

**Comment by HugoZink** [comment]
Fixed.
