### ISSUE TITLE
Reinforce groups do not function correctly

### ISSUE THREAD

**Issue by RedFlamer** [HugoZink/IreNFist#110]
A change to CopLogicIdle._chk_relocate with the addition of Death Sentence in U173 forces enemies with a defend_area objective to immediately move away if there isn't a criminal in their objective area, which means instead of reinforcing an area as intended, they just rush the player.

**Comment by HugoZink** [comment]
Ouch, that's a pretty significant downgrade in their AI.

Thanks a lot for bringing it to my attention! I'll do my best to fix this (and more) in the next update.

**Comment by HugoZink** [comment]
Fixed. Thanks again for the report!
