### ISSUE TITLE
Error Initializing Parts

### ISSUE THREAD

**Issue by Skysteele** [HugoZink/IreNFist#116]
Hello! While I was getting back into payday 2, and updating all my mods, I ran into this "Error Initializing Parts" message, stating that an error occurred while trying to initialize support for custom weapons. This error will not go away, no matter what I do to install and reinstall my custom weapons, or my mods in general. So, I am now posting the error logs. There was definitely something weird, I think the mod was trying to find older files that don't exist? Anyways, here's the logs:

[2021_06_21_log.txt](https://github.com/HugoZink/IreNFist/files/6689012/2021_06_21_log.txt)

Thank you again in advance!

EDIT: I did a bit more testing, and the error does go away when I remove the L115 mod and the AK12 mod. I will keep this open still to see if I can still use the AK12 or the L115. Thanks again!.

**Comment by HugoZink** [comment]
Your log file makes no sense, it appears you may have different issues altogether. You have the game complaining that `NewRaycastWeaponBase` doesn't exist?

Either way it looks like the AK12 or L115 were compatible in the past, but were updated and now no longer works. I'll get on fixing it.

**Comment by Skysteele** [comment]
Yeah. Regardless, I think I fixed the issue. I was scratching my head
looking at it, but it went away after I got rid of those two weapons, and I
updated pocohud3. Thank you for the help!
