### ISSUE TITLE
Weapon charms were introduced in Jiu Feng Smuggler Pack 3 DLC

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#119]
Problem is, they share their name with the renamed stat boosts, leading to... well, this.
![218620_20210924184356_1](https://user-images.githubusercontent.com/70559253/134754496-1211ee41-31a5-4ba5-9418-830640505842.png)

**Comment by HugoZink** [comment]
Yup, I'm aware of the issue. I'm working on a new update to resolve this, as well as adding compatibility for all the new weapons and mods.

**Comment by HugoZink** [comment]
Fixed. The category is now named "Bonus".
