### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Rustbuuket** [HugoZink/IreNFist#121]
[crash.txt](https://github.com/HugoZink/IreNFist/files/7655847/crash.txt)

and

[2021_12_05_log.txt](https://github.com/HugoZink/IreNFist/files/7655849/2021_12_05_log.txt)

thanks a ton!

**Comment by HugoZink** [comment]
And again with this crash. I don't understand what's going on.

Can you try deleting a bunch of your custom weapons until it stops happening? I know that the HX25 grenade launcher makes this happen, among other things. I want to know which mod is causing this shit.

**Comment by morerokk** [comment]
Fixed! Please redownload the latest version.
