### ISSUE TITLE
huh me again 

### ISSUE THREAD

**Issue by thic9000** [HugoZink/IreNFist#14]
welp i deleted the problem weapon and it still does the same crash so i am sending you the new crash file 
[payday2_win32_release_5412799_crash_2020_8_16T1_57_26C0.txt](https://github.com/HugoZink/IreNFist/files/5079845/payday2_win32_release_5412799_crash_2020_8_16T1_57_26C0.txt)

**Comment by HugoZink** [comment]
Looks like another custom weapon mod incompatibility, I'll get on it.

**Comment by HugoZink** [comment]
Fixed in 6c5a37fb722097b8e18c2b52fd65f2bbb150ca30. You should redownload the mod from the Releases page or Mod Workshop.
