### ISSUE TITLE
weapon incompatibility crash.txt

### ISSUE THREAD

**Issue by jhunt883** [HugoZink/IreNFist#16]
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/wpn_parts.lua:387: attempt to index field 'wpnvalues' (a nil value)

SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:268
new() core/lib/utils/coreclass.lua:35
original() lib/tweak_data/weapontweakdata.lua:6188
_init_data_player_weapons() @mods/base/req/core/Hooks.lua:265
original() lib/tweak_data/weapontweakdata.lua:26
old_init() @mods/base/req/core/Hooks.lua:265
original() @mods/Better Bots/betterbots.lua:293
init() @mods/base/req/core/Hooks.lua:188
new() core/lib/utils/coreclass.lua:35
init() lib/tweak_data/tweakdata.lua:531
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3160
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/setups/setup.lua:35
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/setups/menusetup.lua:1
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/entry.lua:13
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
core/lib/coreentry.lua:19

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                        init()  @mods/base/req/core/Hooks.lua:268                   
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/tweak_data/weapontweakdata.lua:6188             
   _init_data_player_weapons()  @mods/base/req/core/Hooks.lua:265                   
                    original()  lib/tweak_data/weapontweakdata.lua:26               
                    old_init()  @mods/base/req/core/Hooks.lua:265                   
                    original()  @mods/Better                                        
                                Bots/betterbots.lua:293                             
                        init()                                                      
@mods/base/req/core/Hooks.lua:188  new()                                               
                                core/lib/utils/coreclass.lua:35                     
                        init()                                                      
lib/tweak_data/tweakdata.lua:531  new()                                               
                                core/lib/utils/coreclass.lua:35                     
lib/tweak_data/tweakdata.lua:3160  require()                                           
                          =[C]  OrigRequire()                                       
       @mods/base/base.lua:153  require()                                           
   @mods/BeardLib/Core.lua:337                                                      
       lib/setups/setup.lua:35  require()                                           
                                =[C]                                                
                 OrigRequire()                                                      
       @mods/base/base.lua:153  require()                                           
                                @mods/BeardLib/Core.lua:337                         
    lib/setups/menusetup.lua:1  require()                                           
                          =[C]  OrigRequire()                                       
       @mods/base/base.lua:153  require()                                           
   @mods/BeardLib/Core.lua:337                                                      
              lib/entry.lua:13  require()                                           
                                =[C]                                                
                 OrigRequire()                                                      
       @mods/base/base.lua:153  require()                                           
                                @mods/BeardLib/Core.lua:337                         
     core/lib/coreentry.lua:19  
-------------------------------

System information:
	Application version : 1.96.909
	CPU : AMD E2-7110 APU with AMD Radeon R2 Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R2 Graphics / aticfx32.dll[8.17.10.1433]
	Language : english
	Memory :     3529MB 8KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speaker/Headphone (Realtek High Definition Audio))

**Comment by HugoZink** [comment]
This seems like a difficult one. Something appears to be triggering WeaponFactoryTweakData:init() before WeaponTweakdata is hooked. Can you post a list of all the other BLT mods you have installed?

**Comment by jhunt883** [comment]
sure.
Stoic armorer (perk deck)
ACR M203
AFSF2
AK-12
AN-94
Armor-healer (another perk deck)
ARX160 A2
Assault (I have no idea what this is)
Attachment descriptions
Beardlib
Better bots
Big lobby 3
Carl's A-list, game-rip, GFL, and shitpost skins
Classic skin pack reborn 1.7.1
Custom attachments for custom weapons
Custom sights support for sights mods
Custom weapon animation fixes
Customfov
Decreased stockpiler
FN Five-seveN MK2
FN SCAR-L
Golden repeater (skin)
Hera arms pack
Improved offline functionality
IRE AND FIST REBORN
Kel-Tec RFB
M45A1 CQBP
Missing textures universal skin
MK-17 MOD 0 (SCAR SSR)
MK-18 specialist
Rainbowmaker/neppu Tennouboshi Death row remix, dead end, jackpot, retribution, moonlight, and operation save the world (all music)
No pager on domination
Perkdecks refund bind
PP-19-01 Vityaz
Predator-lurker (perk deck)
Q honey badger (secondary and primary versions
RPD
SCAR-20
Speedpull mag pack
SVU (secondary version)
Tactical reloading
VEPR-12
Voicline framework
Volta (M4 skin)
Weaponlib

**Comment by Bwamo** [comment]
do you happen to be equipping your bots with custom beardlib weapons?

**Comment by HugoZink** [comment]
I still have no idea which mod would cause this to happen, it will have to wait until the refactoring that I'm doing. Should be starting tomorrow.

**Comment by HugoZink** [comment]
Still happens on occasion, even after the code refactor.

**Comment by HugoZink** [comment]
Most likely solved, please open PAYDAY 2/mods/saves folder and delete `infsave.txt`.
