### ISSUE TITLE
93R Burst Fire crash

### ISSUE THREAD

**Issue by AAAngle** [HugoZink/IreNFist#17]
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/BurstFire.lua:429: attempt to index local 'secondary_weapon_panel' (a nil value)

SCRIPT STACK

set_teammate_weapon_firemode_burst() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:409
_check_action_weapon_firemode() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:381
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:932
original() lib/units/beings/player/states/playerstandard.lua:435
update_original() @mods/base/req/core/Hooks.lua:188
original() @mods/VanillaHUD Plus/lua/BurstFire.lua:302
update_original() @mods/base/req/core/Hooks.lua:265
update() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:350
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     LdrCallEnclave                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

**Comment by HugoZink** [comment]
Who was using the Beretta 93R and who was using the mod? Were they Akimbo Beretta 93R's?

**Comment by Bwamo** [comment]
vanilla hud plus has a setting for enabling burst fire as seen here:
![20200820145037_1](https://user-images.githubusercontent.com/23544898/90812754-94871600-e2f4-11ea-91fe-e3a2fac6cae4.jpg)

below is a zip containing the culprit
[BurstFire.zip](https://github.com/HugoZink/IreNFist/files/5104940/BurstFire.zip)

**Comment by AAAngle** [comment]
Thanks for the help
Also, I was in singleplayer if that still means anything

**Comment by Bwamo** [comment]
doing more testing, I found out that the regular beretta doesn't have any issues but it has 3 fire modes: semi, semi, and full-auto

equipping the 93r with the burst only trigger group, firing with the three round burst crashes the game
