### ISSUE TITLE
C++ Exception

### ISSUE THREAD

**Issue by Vitaenon** [HugoZink/IreNFist#2]
Hello,
I keep getting exception crashes, I've reinstalled and reset my save to test a few times, but they seem to keep coming back.

[crash.txt](https://github.com/HugoZink/IreNFist/files/4967801/crash.txt)

I'm not 100% sure if it's IreNFist's fault, because I'm not entirely sure what to make of the crashlog, which is the same every time.

Only active BLT mods are IreNFist and HoldTheKey. 

I'm going to try to wipe my payday clean one more time to see if it crops up again after that, but I figured I'd make a report. I'll report back if another reinstall seems to fix it or if it happens again.

Thanks for picking the mod up again. :)

**Comment by Vitaenon** [comment]
Reinstall did not work. Again, only SuperBLT, Beardlib and IreNFist are installed.

[crash.txt](https://github.com/HugoZink/IreNFist/files/4968416/crash.txt)

**Comment by HugoZink** [comment]
Hey, and sorry for the late response! I was actually tracking this issue down myself. I believe it should now be fixed, can you test?

**Comment by HugoZink** [comment]
@Vitaenon Hey, and sorry for the late response! I was actually tracking this issue down myself 2 days ago. I believe it should now be fixed, can you test that?

**Comment by HugoZink** [comment]
Confirmed fixed.
