### ISSUE TITLE
Hitting Matt crashes the game

### ISSUE THREAD

**Issue by HugoZink** [HugoZink/IreNFist#29]
Hitting Matt in the safehouse crashes the game. This is literally caused by an attempted anti-crash measure.

For now, please restrain yourselves until this is fixed.

**Comment by millicentilottapede** [comment]
This also happens when hitting Santa in the Stealing Xmas heist.

And since hitting him is mandatory to progress, it cannot be completed.

**Comment by HugoZink** [comment]
I just put in automated unit testing so this sort of stuff won't easily happen again. Worst case, I push something that's broken and Github will simply not build a mod zip, and therefore you won't get an auto-update.
