### ISSUE TITLE
mod caused game to commit not alive

### ISSUE THREAD

**Issue by KillorKitten** [HugoZink/IreNFist#3]
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/wpn_stats.lua:1893: attempt to call method "SetupAttachmentPoint" (a nil value)
[crash.txt](https://github.com/HugoZink/IreNFist/files/4973620/crash.txt)

**Comment by HugoZink** [comment]
Any other mods installed? I'll take a look at it, it's probably compatibility for a custom weapon or a custom weapon mod not working.

**Comment by HugoZink** [comment]
Looks like you need to install WeaponLib. I have added an extra crash guard in case you don't have it installed. Should be fixed in the next commit.

**Comment by HugoZink** [comment]
Fixed in 1b00a92b56f6aa38ae967fe5a5740af7ff16c7e2.
