### ISSUE TITLE
X_Olympic (Akimbo Paras) and SSO Bug

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#32]
Despite having Fast and Furious on the active perk deck,
![payday2_win32_release_2020-09-07_15-25-13](https://user-images.githubusercontent.com/23544898/92413505-7146ce00-f11e-11ea-918a-5e2b0d842035.png)

I am unable to actually purchase them.
![payday2_win32_release_2020-09-07_15-21-44](https://user-images.githubusercontent.com/23544898/92413385-de0d9880-f11d-11ea-9a86-48f135af9c60.png)

game brok pls fix ty

**Comment by HugoZink** [comment]
That's very specific. Does this also happen without InF? I'm not doing anything with the Akimbo Paras on my end.

I checked SSO's code and it should definitely be unlocked. Try restarting your game?

**Comment by HugoZink** [comment]
Mod page seems to confirm that this issue *was* on SSO's end. Try updating in the BeardLib mod manager.

**Comment by Bwamo** [comment]
All good on the eastern front.
