### ISSUE TITLE
crash on mask customization 

### ISSUE THREAD

**Issue by tlcombs2007** [HugoZink/IreNFist#33]
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/wpn_parts.lua:4370: attempt to index a nil value

SCRIPT STACK

init() @mods/base/req/core/Hooks.lua:268
new() core/lib/utils/coreclass.lua:35
original() lib/tweak_data/weapontweakdata.lua:6188
_init_data_player_weapons() @mods/base/req/core/Hooks.lua:265
original() lib/tweak_data/weapontweakdata.lua:26
original() @mods/base/req/core/Hooks.lua:265
init() @mods/base/req/core/Hooks.lua:188
new() core/lib/utils/coreclass.lua:35
init() lib/tweak_data/tweakdata.lua:531
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3157
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/setups/setup.lua:35
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/setups/menusetup.lua:1
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
lib/entry.lua:13
require() =[C]
OrigRequire() @mods/base/base.lua:153
require() @mods/BeardLib/Core.lua:337
core/lib/coreentry.lua:19

this is the crashlogs if you need them

**Comment by HugoZink** [comment]
Are you positive this crash.txt is from mask customization? It seems more like support for a custom weapon that's been made outdated. I'll take a look regardless.

**Comment by HugoZink** [comment]
I tested mask customization again and it works just fine. I'll take a look at the particular line from the crash report.

**Comment by HugoZink** [comment]
That line doesn't cause crashes on my end. This issue seems to be invalid.

If you're sure the crash is caused by InF, double-check that the file you're posting is `crash.txt`, not `crashlog.txt`.
