### ISSUE TITLE
No AK-12 Burst Fire

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#34]
The vanilla AK-12 lacks the 2-round burst trigger groups.

![218620_20200907182205_1](https://user-images.githubusercontent.com/70559253/92423955-bfb49680-f137-11ea-83c8-4f8c9f9349d0.png)

**Comment by Bwamo** [comment]
The AK-400 (AK-74M upgrade) AK-12 does not have burst capabilities. The AK-12 Prototype has what you probably want and it's a separate mod on the workshop. 
https://modworkshop.net/mod/17262

**Comment by Bwamo** [comment]
> The AK-400 (AK-74M upgrade) AK-12 does not have burst capabilities. The AK-12 Prototype has what you probably want and it's a separate mod on the workshop. 
> https://modworkshop.net/mod/17262

Nevermind, turns out the final production model does actually have a 2rnd burst. Always thought it was Full/Semi only, but that's cool

**Comment by HugoZink** [comment]
Sounds good. Will put into next update.

**Comment by HugoZink** [comment]
Added in the latest commits.
