### ISSUE TITLE
Can't buy all assets with IreNFist prices in effect.

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#36]
Probably has to do with the prices being $0 mayhaps. Can purchase all assets fine if IreNFist price modifying is off.

**Comment by HugoZink** [comment]
This is a known issue and is actually part of the reason why I made a toggle for the prices to begin with.

I could make the assets cost either $1 or $10 as a way around this. I really don't feel like rewriting the Buy All Assets code.

**Comment by HugoZink** [comment]
Fixed in fd14befa1f01cb6e32ef3b968e367f420be738a2.

The game now counts if the amount of unlockable assets is more than zero, not "if their cost is bigger than zero".
