### ISSUE TITLE
Galil Floating Bipod

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#38]
A bipod floats somewhere on the map when the weapon itself is equipped. Bug occurred with the Tzalafim Handguard equipped.
![20200911131159_1](https://user-images.githubusercontent.com/23544898/92968454-293ee880-f449-11ea-9557-c998fb9366cd.jpg)

**Comment by HugoZink** [comment]
Lol

**Comment by HugoZink** [comment]
This looks like some sort of attachment point issue. The bipod oughta be a "dummy" one to begin with so this shit can't happen. Thanks for your report!

**Comment by HugoZink** [comment]
Fixed.
