### ISSUE TITLE
Possible incompatibility with Keepers/Goonmod waypoints mod by TDLQ and invisible weapons for Zeal units bug

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#39]
1. With Keepers mod, Converted Cops no longer move to the desired waypoint, even if I shouted at them many times. And this issue seemed to happen if I have the IREnFist mod installed. There's also a rare issue in Reservoir Dogs Day 2 on the storage room on the left side where bots and Converted Cops won't move to the area at all.

2. Invisible weapon(s) bug occurs on light Zeal units--possibly shotgunners. This could be from the mod itself or another incompatibility from other mods. I did try to remove mods that might cause this issue but to no avail.|

A). Invisible Shotgun(?) bug:
![image](https://user-images.githubusercontent.com/71377805/93317842-20c72300-f838-11ea-96ef-57759b7f1033.png)
![image](https://user-images.githubusercontent.com/71377805/93317968-4e13d100-f838-11ea-97bb-b6bef35c397a.png)

B). Keepers incompatibility:
https://youtu.be/MGdMJlTvHSA

And for your information, I also have Better Bots, Monkeepers, and The Fixes mods installed. That might be the root of the issue.

I hope these issues can be fixed with the next update, or otherwise, I'll have to remove Keepers mod.

**Comment by HugoZink** [comment]
I use Better Bots all the time so that should work.

InF doesn't work well with Iter and therefore Iter should be disabled (but kept installed to satisfy Keepers). In turn, this may cause Keepers to add oddly. I'll see what I can do about this.

The invisible weapon thing is new to me, I'm not sure why that's happening. I'll look into it, thanks.

**Comment by HugoZink** [comment]
It should be noted that I brought up the issues with Iter and Full Speed Swarm many times with TdlQ. His response was to ignore the problem.

Nearly all of his mods carry an absolute fuckton of feature creep with them (such as automatically **banning** players for using incendiary melee weapons or "invalid" custom weapons, or breaking the cop flank/hold AI, forcing cops to always rush directly at the players), and it has the tendency to break with other mods installed.

**Comment by Siellenexia** [comment]
Thank you for your response and your attempt to fix the issues.

That's unfortunate and explains his and his mods sudden disappearance from modworkshop. I don't have Iter installed ever since I used this mod, and I only used TDLQ's Monkeepers and Keepers mods prior to this report. And that's because I play solo most of my time. Still, I understand why it may be arduous to solve the incompatibility issues.

As of now, I already removed Keepers, but I kept Monkeepers since I don't have an issue with it. However, your statements regarding TDLQ's mods make me inclined to remove it. 

Also, it is worth pointing out that the invisible weapon bug didn't occur with the previous version(s) of IREnFist.

**Comment by Bwamo** [comment]
To add to this, I've noticed a few Murkywater npcs running around without a weapon as well. Also only started noticing it after the Zeal Shotgunner update.

**Comment by HugoZink** [comment]
It's probably something going wrong in their weapon replacement code. This code only runs on DS though. Does it also happen below DS? @Bwamo

**Comment by Siellenexia** [comment]
I'll try to scrutinize this issue further, and I found something even more fascinating. The invisible weapon doesn't occur on Zeal or Death Sentence's shotgunners and seems to be random.

First, I tried to dominate and convert a light Zeal unit with an invisible weapon. The intention was to examine whether this bug occurs on shotgunners and/or Death Sentence units only or not:
![payday2_win32_release_mya7x82UoF](https://user-images.githubusercontent.com/71377805/93368288-f9904600-f877-11ea-84e1-ea49c6600e95.png)
dom.

However, after I converted them, the weapon appeared:
![payday2_win32_release_aVObBJBqwj](https://user-images.githubusercontent.com/71377805/93368454-36f4d380-f878-11ea-9314-b257e3789351.png)

**Comment by Siellenexia** [comment]
Further evidence:
![Uploading payday2_win32_release_2OX2P0WO2P.png…]()
![payday2_win32_release_bNxNYBhXNd](https://user-images.githubusercontent.com/71377805/93369957-512fb100-f87a-11ea-82d7-d0cd369ff1d5.png)

This bug does not occur on Death Wish or below.

**Comment by HugoZink** [comment]
There's probably _some_ Zeal unit supplied in Overkill's broken/unused spawngroups that's actually totally broken, which makes sense because DS was added after they broke them. Most likely it's a wrong unit file or something. I can probably force-give these guys a weapon and fix any invalid unit paths.

**Comment by HugoZink** [comment]
Thanks a lot for your testing and helping narrow it down, it's very much appreciated!

**Comment by Bwamo** [comment]
Was able to reproduce it as well
![20200916135516_1](https://user-images.githubusercontent.com/23544898/93385342-23277e00-f834-11ea-9772-df0357ddb5a2.jpg)
![20200916135822_1](https://user-images.githubusercontent.com/23544898/93385345-2458ab00-f834-11ea-9cf9-0dc2142b8caf.jpg)

Can also confirm that dominating and converting them does give them an MP5.
![20200916144246_1](https://user-images.githubusercontent.com/23544898/93385470-4fdb9580-f834-11ea-9b70-e8dec24aeb0c.jpg)
![20200916144301_1](https://user-images.githubusercontent.com/23544898/93385475-510cc280-f834-11ea-8303-451b978ed21e.jpg)

**Comment by HugoZink** [comment]
It's rather strange that this is happening to just the MP5 dudes. Does it only happen to them? I can patch over that quite easily but I honestly have no clue why they'd spawn without a weapon sometimes.

**Comment by Siellenexia** [comment]
Hmm, Shotgunners on both DW and DS worked fine from what I've tested, the same goes with blues with CAR-4 and UMP45s. I'm unsure if there are units with MP5s on Death Wish, but I will let you know if there's an issue.

**Comment by HugoZink** [comment]
I was going to push an update to forcibly fix this last night, but I got sidetracked into the squad/enemy stuff a little so it'll have to wait for just a bit. Expect a fix for the invisible/missing weapons soon! Thanks for your investigative work, it's very much appreciated.

I'll make sure to work on the Keepers/Iter stuff tonight as well.

**Comment by Siellenexia** [comment]
That's nice! Thank you for addressing these issues.

**Comment by HugoZink** [comment]
[Issue is currently being tested on the experimental branch.](https://github.com/HugoZink/IreNFist/archive/experimental.zip) I'm testing this myself too, if all goes well I'll merge it to main.

You can extract the `IRE AND FIST REBORN` folder into your `PAYDAY 2/mods` folder. It might be best to remove the existing folder first.

**Comment by Siellenexia** [comment]
Unfortunately, the issue still persists:
![payday2_win32_release_U3H2dggB0A](https://user-images.githubusercontent.com/71377805/93506836-0465dc00-f947-11ea-9501-4fa718cdb404.png)

![payday2_win32_release_EDUJV1Q6XB](https://user-images.githubusercontent.com/71377805/93506861-10ea3480-f947-11ea-85d2-f993b5eb73b7.png)

**Comment by HugoZink** [comment]
That's quite odd.

Regardless, I'll be merging the experimental build into the main branch since it's been confirmed to not crash. I'll work on this issue some more.

**Comment by HugoZink** [comment]
Does the enemy invisible weapons happen with InF's rainbow assaults disabled? I have a suspicion that this is related to lighter units spawning on DS with the "rainbow assaults" feature enabled.

You don't have to disable all assault tweaks, just the "rainbow assaults".

**Comment by Siellenexia** [comment]
Is it for the enemy variety option?

**Comment by HugoZink** [comment]
I think I found the issue, I'll just have to do a bit more testing.

It seems to no longer happen if I take out the weapon replacement code. Most likely it's this code that's bugged, and those lighter units with invisible weapons were actually just light shotgunners. I'll probably have a fix soon.

**Comment by HugoZink** [comment]
Also if you found another bug, feel free to report it in a separate issue.

**Comment by Siellenexia** [comment]
Gladly.

**Comment by HugoZink** [comment]
I did indeed find the issue, but sadly in order to fix it I'll temporarily have to rid the DS units of their shotgunners. I'll get a fix out soon.

**Comment by HugoZink** [comment]
Disregard, looks like I *was* able to fix this completely, and they even get to keep their shotguns! Will push update soon-ish.
