### ISSUE TITLE
Crash with Illuminated Iron Sight Pack

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#4]
illuminated iron sight pack doesn't seem to work with irenfist

[crash.txt](https://github.com/HugoZink/IreNFist/files/4976748/crash.txt)

problem arises here in wpn_parts
![notepad++_2020-07-25_18-23-21](https://user-images.githubusercontent.com/23544898/88467324-f8f4b800-cea3-11ea-9edb-a2641e6d37fe.png)

**Comment by HugoZink** [comment]
Thanks, looking into this.

**Comment by HugoZink** [comment]
Fixed in 1b00a92b56f6aa38ae967fe5a5740af7ff16c7e2.
