### ISSUE TITLE
Wrong stats on PX4 Storm' ammo types

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#42]
Like I said before, I started checking supported custom weapons. 

In this case, I believe that these ammo types were supposed to drop this pistol to 55/170 tier, but they aren't.

![20200918214943_1](https://user-images.githubusercontent.com/34880333/93634429-40f21000-f9f9-11ea-9042-9f2fd6f9342f.jpg)
![20200918214947_1](https://user-images.githubusercontent.com/34880333/93634439-42233d00-f9f9-11ea-9c85-336383bc2c3a.jpg)

**Comment by HugoZink** [comment]
Yep, the first one is supposed to drop it down to Light Pistol tier. .45 Super, if experience serves, was supposed to raise it to "supermedium", a hidden category reserved for a select few custom pistols. I'll take a look at this, thanks!

**Comment by HugoZink** [comment]
Fixed in 0df825bb878f8b9cb8baf04a23c87b6645dec0ac.
