### ISSUE TITLE
Incorrect keybind description for sniper bipods

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#43]
![image](https://user-images.githubusercontent.com/71377805/93659747-cb2a8a80-fa72-11ea-8e21-ae789b6d73ad.png)

On the description for a sniper bipod, it says, "Press [Gadget Key] to deploy" instead of the "deploy bipod" key. I thought it was intentional, but when I pressed the gadget key, it didn't work, and it only deployed with the default key (4) instead.

Here's for LMG bipods:
![image](https://user-images.githubusercontent.com/71377805/93659831-a8e53c80-fa73-11ea-97fc-de7ca2dfa77c.png)

**Comment by HugoZink** [comment]
I noticed this one too. Thanks for your report!

**Comment by Siellenexia** [comment]
No problem! I really love this mod and will look further for possible bug fixes, improvements, and whatnot.

**Comment by HugoZink** [comment]
Fixed.

**Comment by HugoZink** [comment]
It's not fixed on the McMillan CS5, possibly more. Not sure why.

**Comment by HugoZink** [comment]
Fixed on the McMillan CS5.
