### ISSUE TITLE
Chiappa Rhino 60DS : wrong ammo type' stats

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#44]
Aaand it's me again with custom weapons. 
This time - the "ugly" revolver:
![20200919135417_1](https://user-images.githubusercontent.com/34880333/93665679-282d3d00-fa81-11ea-8faa-f113ccb50566.jpg)
Since it's .40 S&W, I guess it should drop damage down to medium (or supermedium?) tier, instead to light tier (55 dmg revolver, nice). 

P.S By the way, I don't checking supported custom weapons that are "unlisted" right now on MWS - just in case if they'll be updated.

**Comment by HugoZink** [comment]
This is probably the same issue as the other one, where the weaponmod incorrectly has stats *and* a weapon-specific override. This should be an easy fix now. Thank you for the report, it's very appreciated!

**Comment by HugoZink** [comment]
Fixed.
