### ISSUE TITLE
FABARM STF-12 Compact - wrong stats on long barrel.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#45]
And another one. 
Just as title says:
![20200920103025_1](https://user-images.githubusercontent.com/34880333/93706263-1b662300-fb2d-11ea-810f-bc77ccb9e352.jpg)
After using INF for a long time, I get it that longer barrels give accuracy/stability at the cost of concealment and vice versa with short ones.
But not with this shotgun. Short barrel is correct:
![20200920103301_1](https://user-images.githubusercontent.com/34880333/93706316-a7784a80-fb2d-11ea-8099-9d956b52c7a0.jpg) (Even tho I still don't know if it should give damage, but it's up to you)

**Comment by HugoZink** [comment]
I can't find this shotgun, which one is this?

**Comment by MrVavlo** [comment]
Oops, sorry. It's [FABARM STF-12](https://modworkshop.net/mod/23188). I don't use any renaming mods, so I don't know why it has different name in black market...

**Comment by HugoZink** [comment]
Thanks, I'll take a look at it in the next update.

**Comment by HugoZink** [comment]
Fixed.
