### ISSUE TITLE
Shockproof Aced skill crash with poison bolts

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#46]
Title.

Here's the log:
Application has crashed: C++ exception
[string "core/lib/utils/corecode.lua"]:100: attempt to index local 'obj' (a number value)

SCRIPT STACK

add_damage_result() lib/units/weapons/bowweaponbase.lua:259
damage_tase() lib/units/enemies/cop/copdamage.lua:1671
give_impact_damage() @mods/IRE AND FIST REBORN/lua/raycast.lua:965
on_collision() lib/units/weapons/raycastweaponbase.lua:2137
on_collision() lib/units/weapons/raycastweaponbase.lua:2801
_on_collision() lib/units/weapons/projectiles/arrowbase.lua:76
clbk_impact() lib/units/weapons/projectiles/projectilebase.lua:256
func() lib/units/weapons/projectiles/arrowbase.lua:95
body_collision_callback() core/lib/units/coreunitdamage.lua:1537
lib/units/unitdamage.lua:92

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by Siellenexia** [comment]
I reckon this is correlated with "While being tased, your bullets will electrify enemies."

**Comment by HugoZink** [comment]
That's rather interesting. Thanks for the report! I'll make sure to get it fixed for the next update.

**Comment by HugoZink** [comment]
Fixed.
