### ISSUE TITLE
HK416 - incorrect stats on handguard.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#47]
_Hope I'm not boring you with those stupid custom weapons..._

![20200921165321_1](https://user-images.githubusercontent.com/34880333/93776800-a11cc800-fc2c-11ea-8237-0f1bd7281728.jpg)
![20200921165323_1](https://user-images.githubusercontent.com/34880333/93776808-a2e68b80-fc2c-11ea-827f-84c47aa5d23d.jpg)
M27 IAR is shorter that Geissele 14.5" but gives more accuracy with less concealment penalty. Same story with Geissele 10.5" - it has only 1 accuracy with -1 concealment.

**Comment by HugoZink** [comment]
I went over all the HK416 handguard stats again and it seems they're all correct already. The next version will fix Vanilla Mod Pack's HK416 though.

**Comment by Bwamo** [comment]
> Confirmed, will fix for next release.
> 
> Just for my personal reference: the vanilla mod pack's HK416 has issues with reload timers and the "flipturn". I'll look at both of these.

to add to the reload timers issue, the Hornet .300 rifle in vanilla mod pack 2 has the same issue

**Comment by HugoZink** [comment]
Thanks, I'll take a look at the hornet too.
