### ISSUE TITLE
Marlin Model 1894 Custom - extra concealment on default iron sights?

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#49]
And it's me again.

Guess this was intended, since I'm seeing this for first time using IreNFist, but:

```
	self.parts.wpn_fps_snp_m1894_irons.stats = {
		value = 0,
		zoom = 0,
		concealment = 3
	}
```
Maybe it's better to remove/include to the rifle itself those 3 concealment? 

I would pass this issue away quietly, but I'm using [Iron Sights Pack](https://modworkshop.net/mod/17205), and losing 3 conc. just because I wanted different iron sights is kinda strange.

**Comment by HugoZink** [comment]
This is probably a hacky workaround for the fact that the Marlin is technically a sniper, and it shouldn't *add* concealment when you put a big scope on it like with the other snipers. I'll take a look at it because I think I fixed/standardized this already.

**Comment by HugoZink** [comment]
Surprise: the MK 14 EBR and marlin issues somehow aren't even related. I'm totally mystified on why the marlin does this, but at least I fixed it for the Mk14.

**Comment by HugoZink** [comment]
Fixed in the next update.
