### ISSUE TITLE
HoxHud Damage Popup Standalone Incompatibility

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#5]
Crash occurred after a kill
![notepad++_2020-07-26_20-28-57](https://user-images.githubusercontent.com/23544898/88493361-a936ef00-cf7e-11ea-859e-1b8bb6842739.png)

**Comment by HugoZink** [comment]
Does this happen without HoxHud damage popup standalone? Will look into this, thanks.

**Comment by HugoZink** [comment]
Cannot and will not fix. This mod is closed-source and therefore I cannot even *see* what might be going wrong.

Go ask Olipro to open-source his code and then we'll talk.
