### ISSUE TITLE
MK 14 EBR - sights with wrong concealment stat.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#50]
Almost the same problem like in #49 - this is not the usual sniper rifle.
![20200925113756_1](https://user-images.githubusercontent.com/34880333/94245898-995a6d80-ff23-11ea-92b6-1ad899493be2.jpg)
All sights give extra concealment, despite having iron sights by default.

**Comment by HugoZink** [comment]
Thanks, I'll take a look at it.

**Comment by HugoZink** [comment]
Fixed. The Mk14 EBR probably had an actual scope by default at some point which is why this happens.
