### ISSUE TITLE
QBZ-97B - Crash on loading

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#53]
_Boi, I'm on the roll today with those..._

```
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/wpn_parts.lua:4822: attempt to index a nil value

```
[Here's the full crashlog](https://github.com/HugoZink/IreNFist/files/5287013/crash.txt)

> 	-- fuck these sights

**Comment by HugoZink** [comment]
Thanks, I'll take a look at it. As mentioned before, fixing this will probably involve removing weaponmod support for this particular weapon.

**Comment by HugoZink** [comment]
Fixed.
