### ISSUE TITLE
Cannot be uncuffed when arrested while interacting with objectives

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#54]
See title.

Neither bots nor players were able to release me, despite the message displaying on my screen saying they did.
![20200928144148_1](https://user-images.githubusercontent.com/70559253/94489449-51448080-0199-11eb-82c9-de0ae86f2c50.jpg)
The timer is gone as well; not sure if this is intentional.

**Comment by HugoZink** [comment]
Aw fuck

**Comment by HugoZink** [comment]
This definitely isn't intentional, and this also didn't show up in my tests. Sorry about that!

I really should have added a menu option for this sooner, but for now you can set `enableNewCopBehavior` to `false` in your `PAYDAY 2/mods/saves/infsave.txt` file to disable this feature.

**Comment by HugoZink** [comment]
For now, this code has been temporarily disabled as an emergency workaround. I'll make sure to test this more thoroughly when reimplemented.

**Comment by millicentilottapede** [comment]
No worries. I do like the idea of cops cuffing you when you're doing objectives as it puts additional strain on players who don't watch their backs.

**Comment by HugoZink** [comment]
Fixed.
