### ISSUE TITLE
No option for disabling wall running or the entirety of Advanced Movement Standalone(?)

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#56]
![image](https://user-images.githubusercontent.com/71377805/94783313-b517b500-03f6-11eb-9a2c-67c002862b42.png)

This is not exactly an issue but more of a preference.

I couldn't find an option that disables the wall running. Wall running and other advanced movement's features (for me at least) can be a nuisance, especially in Stealth heists where I would accidentally wall run and either fall down or break something. 

If this was intentional, then I hope you can implement an option to disable it. Thank you.

**Comment by HugoZink** [comment]
This is a known issue. I had intended to turn the wallrunning into a (tier 0/tier 1) skill instead, but I decided against it. I'll add a toggle for it.

**Comment by Siellenexia** [comment]
Thanks for the response. I also like to point out that disabling advanced movement makes the "Close Range Assault" skill useless. I wonder if you can change this as well(?)

**Comment by HugoZink** [comment]
I'm not sure if I want to change Close Range Assault since it would have to be *something else* if adv. movement is disabled, and I really like it as-is. It's probably a replacement for the shotgun mag size increase which was an absolute travesty.

**Comment by HugoZink** [comment]
There is now a menu toggle for Wallrunning, which also toggles walljumping and clinging on/off.
