### ISSUE TITLE
Question regarding Shotgunners' damage on Death Sentence difficulty

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#59]
On Death Sentence, shotgunners can one-shot heisters and obliterate Jokers hastily as well, even if you have the Partners in Crime Aced skill. I was wondering if this was intended since Shotgunners can spawn in groups, and in some heists, it's frustratingly difficult to avoid getting shot by them. 

(However, if this was intended, may I provide a suggestion to reduce their damage and range further?)

Edit: I can confirm that Jokers are practically useless on Death Sentence since they die in a matter of seconds by Shotgunners.

**Comment by HugoZink** [comment]
DS is a meme, and the default shotgunners on DS are actually slightly less hard-hitting than the default riflemen. The problem arises in the fact that InF nerfs the riflemen to a more reasonable level, but doesn't nerf the shotgunners.

I will be correcting this soon. I will also slightly reduce the shotgun squad spawn chance, since I don't like them being 50/50.

**Comment by Siellenexia** [comment]
No problem. I play on Death Sentence for achievement purposes. At first, I thought it was intended for Shotgunners to deal a lot of damage. But then I started to play on cramped, yet exposed heists like The Biker Heist Day 2 and Cursed Kill Room, and that's when I noticed that Shotgunners are a bit overpowered. 4 of them can also spawn along with a Medic. Interestingly enough, Medics don't deal the same damage as Zeal shotgunners.

And with the addition of harder domination, it was a frustrating experience to finish those heist, not to mention that Jokers die hastily anyway.

**Comment by HugoZink** [comment]
Fixed in the next version. InF already nerfed their damage but apparently this wasn't enough.

**Comment by Siellenexia** [comment]
I'd say it's far more doable now, but Jokers still struggle against Shotgunners, even on Death Wish. This is due to the fact that they can get knocked back easily but unable to get up since Shotgunners spawn in groups. This is sort of an issue for users who rely on Jokers for Health Regeneration

**Comment by HugoZink** [comment]
The next version with the actual shotgunner fixes isn't uploaded yet sadly.

**Comment by Siellenexia** [comment]
That's great to hear. Thanks for the quick update o7

**Comment by HugoZink** [comment]
Fixed.
