### ISSUE TITLE
Missing Flavor Text

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#6]
various flavor text descriptions are missing for post-border crossing heist content including outfits and gloves
![payday2_win32_release_2020-07-26_20-31-44](https://user-images.githubusercontent.com/23544898/88493526-9a9d0780-cf7f-11ea-83ce-074963d4eb16.png)
![payday2_win32_release_2020-07-26_20-34-52](https://user-images.githubusercontent.com/23544898/88493529-9bce3480-cf7f-11ea-8b78-79f99bbb6897.png)
![payday2_win32_release_2020-07-26_20-03-44](https://user-images.githubusercontent.com/23544898/88493782-03d14a80-cf81-11ea-8801-220ff4d9b3bd.png)

**Comment by HugoZink** [comment]
Do the outfits normally have flavor text in vanilla? This might be a bug with how IreNFist overrides the *entire* blackmarket text description function. Will look into this.

**Comment by Bwamo** [comment]
> Do the outfits normally have flavor text in vanilla? This might be a bug with how IreNFist overrides the _entire_ blackmarket text description function. Will look into this.

Yes, outfits and gloves normally do have text as well as an indicator from which DLC the item is from.

**Comment by HugoZink** [comment]
I confirmed the issue and I am currently working on a fix. Thanks for your report!

**Comment by HugoZink** [comment]
Fixed in 5cc26fe8f6f7e5378d9a4cf26a16cfb7bf821360.
