### ISSUE TITLE
Compact-5 (Primary/Secondary) - The Ninja Barrel isn't incompatible with all barrel extensions

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#60]
...which leads to the opportunity for stats abuse. 
![20201007112612_1](https://user-images.githubusercontent.com/34880333/95306760-79666a80-0890-11eb-8c66-a846f0520648.jpg)
![20201007112619_1](https://user-images.githubusercontent.com/34880333/95306765-7a979780-0890-11eb-92fd-5a43e73cd399.jpg)

**Comment by HugoZink** [comment]
You are correct. That's quite odd though, does vanilla not do this? Either way, I'll fix this for the next release.

**Comment by HugoZink** [comment]
Deconfirmed, this does not happen on my end. Most likely you have some other mod causing this.
![image](https://user-images.githubusercontent.com/5961617/95641369-2a901f00-0aa2-11eb-9f19-1bedb5c5fff3.png)
