### ISSUE TITLE
Crash after getting incapacitated by a Cloaker

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#61]
Wed Oct 07 23:24:20 2020

Application has crashed: C++ exception
[string "lib/units/beings/player/states/playerarrested..."]:210: attempt to index a nil value

SCRIPT STACK

_check_action_interact() lib/units/beings/player/states/playerincapacitated.lua:174
_update_check_actions() lib/units/beings/player/states/playerincapacitated.lua:147
original() lib/units/beings/player/states/playerstandard.lua:435
original() @mods/base/req/core/Hooks.lua:188
update_original() @mods/base/req/core/Hooks.lua:265
update() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:350
update() lib/units/beings/player/states/playerincapacitated.lua:94
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265

**Comment by Siellenexia** [comment]
This occurred on Death Wish in Golden Grin Casino

**Comment by HugoZink** [comment]
So you got cloaked while interacting with an object? That probably caused the crash. Interesting, I'll try and see if I can reproduce this locally.

**Comment by Siellenexia** [comment]
I think I was trying to dominate and convert a cop, so it could be the reason why it crashed. But I vaguely remember. I also did check if The Fixes mod caused this issue, but I had no luck with that.

**Comment by HugoZink** [comment]
This would be very hard for an end-user to reproduce normally, since you can't exactly get cloaked on demand (let alone while interacting). It's easy for me to reproduce since I can just bind "get cloaked" to a key in a debug mod, and see what happens.

Don't worry about testing this further, I've got a fix ready for tonight.

**Comment by HugoZink** [comment]
I can't really reproduce this and I don't have confidence that the fix works, looking into it further.

**Comment by HugoZink** [comment]
I have been unable to reproduce this, and the code points to vanilla game code. If this happens again notify me and I'll provide a "debug mod" that will give me a clearer crash log.
