### ISSUE TITLE
AI is able to use Inspire to uncuff the player(?)

### ISSUE THREAD

**Issue by ShelbyXIV** [HugoZink/IreNFist#62]
I got cuffed by a Murky while interacting and got uncuffed by Scarface through Inspire. This also triggered the Inspire cooldown for AIs.

I'm actually not sure if this is possible in vanilla in Crime Spree mode where you get cuffed by a Cloaker. Regardless, can you clarify and look into it? Thanks.

**Comment by HugoZink** [comment]
This happens with normal cuffing in vanilla too, it's just incredibly rare. I'll change this, or at least try to. Thanks!

**Comment by Siellenexia** [comment]
A bit irrelevant, but apparently, the cuff works even if the host doesn't have the mod; Was this intentional?

**Comment by HugoZink** [comment]
This was intentional yes, it's also the only way I was able to get this working properly. I could build in a little "does host have InF check" if you really want to.

**Comment by Siellenexia** [comment]
Nah, I just wanted some clarification.

**Comment by HugoZink** [comment]
I looked into this, but the AI inspire code is a hot mess. It's not worth fixing as this would break compatibility with quite a few different mods.
