### ISSUE TITLE
Host crashes when a turret is destroyed

### ISSUE THREAD

**Issue by AbsolofDarkness** [HugoZink/IreNFist#63]
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/sentrygundamage.lua:42: attempt to index global 'turret_unit' (a nil value)

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:109
ProcessAllPeers() @mods/base/req/core/Networking.lua:189
ProcessChatString() @mods/base/req/core/Networking.lua:176
func() @mods/base/req/core/Networking.lua:165
Call() @mods/base/req/core/Hooks.lua:109
_receive_message() @mods/base/lua/ChatManager.lua:12
receive_message_by_peer() lib/managers/chatmanager.lua:68
lib/network/base/handlers/connectionnetworkhandler.lua:662

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by AbsolofDarkness** [comment]
For context, me and my friend both have most up to date version of mod. when I destroy a turret (SWAT Turret or Murky Turret), he will CTD, I will not crash, but will fail the mission due to host leaving.

**Comment by HugoZink** [comment]
Ouch, sorry about that. I haven't been able to reproduce this myself but I will add some extra crash guards to prevent this.

**Comment by HugoZink** [comment]
A fixed version should now be available in the auto-updater.
