### ISSUE TITLE
M308's default AP ammo allows auto-fire(?)

### ISSUE THREAD

**Issue by ShelbyXIV** [HugoZink/IreNFist#64]
For the description of the non-AP ammo, it says, "enables fully-automatic fire." I thought this implies that the AP-ammo does not have an automatic fire mode, but when I tested it, I can still switch between single-shot mode and automatic mode.

If this was intentional, then it may be unnecessary to put it for the non-AP ammo.

**Comment by HugoZink** [comment]
It's probably not intentional for the M308 to have access to auto-fire (none of the other DMR's do), so I'll restrict that. Thanks for the report!

**Comment by HugoZink** [comment]
Fixed.

**Comment by HugoZink** [comment]
There's just one thing to note here, the HUD will still display that you "can't switch firemode" (the subtle red firemode indicator) with the surplus ball ammunition, even though you can. Fixing this would bring more issues.
