### ISSUE TITLE
Cops are able to chase you and cuff you in stealth

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#67]
This occurs even if you aren't detected by them. I noticed this on Election Day, Day 2 when Guards chased me while interacting behind them. I'll send a video soon.

(I might be wrong, but this also caused performance issues on my end)

**Comment by Siellenexia** [comment]
https://youtu.be/81x5eQmcYQk

**Comment by HugoZink** [comment]
LMAO, that's great. Sorry.

This is already fixed on the beta version, but I'm assuming I forgot to push the stealth fix to master. Sorry about that! Please refer to this beta build for a fix: https://github.com/HugoZink/IreNFist/issues/66

If it still happens on the beta build (unlikely), you can turn the Cop Behavior changes off there entirely. If you don't want to switch to the beta build, you can go to `PAYDAY 2/mods/saves`, edit infsave.txt, and change `enablenewcopbehavior` to `false`.

**Comment by HugoZink** [comment]
As for your performance issues, if your PC is low-end, I strongly recommend enabling "Think Faster" in the options, but setting the task throughput to the minimum of 100. This should perform just a little bit better than vanilla. If not, you could turn off the Think Faster feature entirely.

**Comment by HugoZink** [comment]
Actually disregard the beta, after some thoughts I have decided to just merge the build into master. You should get an auto-update soon.

**Comment by Siellenexia** [comment]
No worries. It made me chuckle as well.

As for the Think Faster option, enabling it actually decreases my performance, even though I have the task throughput set to 100.
