### ISSUE TITLE
Random crash on Panic Room on Death Sentence

### ISSUE THREAD

**Issue by Siellenexia** [HugoZink/IreNFist#69]
Tue Oct 13 21:27:00 2020

Application has crashed: C++ exception
mods/IRE AND FIST REBORN/utils/coputils.lua:127: attempt to compare nil with number

SCRIPT STACK

func() @mods/IRE AND FIST REBORN/lua/playerstandard.lua:3400
_start_action_interact() @mods/base/req/core/Hooks.lua:268
_check_action_interact() lib/units/beings/player/states/playerstandard.lua:2272
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:977
original() lib/units/beings/player/states/playerstandard.lua:435
update_original() @mods/base/req/core/Hooks.lua:188
original() @mods/VanillaHUD Plus/lua/VanillaHUD.lua:850
update_original() @mods/base/req/core/Hooks.lua:265
update() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:350
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265

It may be related to the cop cuffing attempt since I was trying to take a bunch of planks.

**Comment by HugoZink** [comment]
Oh whoops, I just realized I made a subtle mistake in my code. My bad!

For now to stop the crashing, please disable Behavior Tweaks in the InF options. Once I push the next update, this should be fixed.

**Comment by HugoZink** [comment]
Fixed, the feature should be safe to enable again.
