### ISSUE TITLE
Random crashing on Birth of Sky

### ISSUE THREAD

**Issue by AbsolofDarkness** [HugoZink/IreNFist#70]
I have no idea what's going on at the time of crashing unfortunately, but it happened twice in the same mission, host did not crash however.

Application has crashed: C++ exception
mods/IRE AND FIST REBORN/utils/coputils.lua:209: attempt to call method 'id' (a nil value)

SCRIPT STACK

func() @mods/IRE AND FIST REBORN/utils/coputils.lua:239
Call() @mods/base/req/core/Hooks.lua:109
ProcessSinglePeer() @mods/base/req/core/Networking.lua:198
ProcessChatString() @mods/base/req/core/Networking.lua:179
func() @mods/base/req/core/Networking.lua:165
Call() @mods/base/req/core/Hooks.lua:109
_receive_message() @mods/base/lua/ChatManager.lua:12
receive_message_by_peer() lib/managers/chatmanager.lua:68
lib/network/base/handlers/connectionnetworkhandler.lua:662

**Comment by HugoZink** [comment]
Related to the new cop behaviors. For some reason I keep running into more and more things that are nil when they shouldn't be. I'll get a fix ready now. Thanks for your report!

**Comment by HugoZink** [comment]
For now this issue should be fixed (or at least the crashing should stop). Thank you for your patience!

**Comment by AbsolofDarkness** [comment]
No problem! I've coded before, even modded some mods, so I know how it feels :P
