### ISSUE TITLE
Crash on the Big Bank online

### ISSUE THREAD

**Issue by ShelbyXIV** [HugoZink/IreNFist#71]
I was the host. My friend was interacting with a Doctor bag and then the game crashed.

Current thread: Main
Script stack:
            on_new_objective()  lib/units/enemies/cop/logics/coplogicbase.lua:412   
            on_new_objective()  lib/units/player_team/logics/teamailogicbase.lua:66  
            on_new_objective()  lib/units/player_team/logics/teamailogicidle.lua:478  
               set_objective()  lib/units/enemies/cop/copbrain.lua:265              
                    origfunc()  lib/managers/group_ai_states/groupaistatebase.lua:3324  
     objective_complete_clbk()  @mods/The                                           
                                Fixes/groupaistatebase.lua:7                        
                        clbk()                                                      
lib/units/enemies/cop/logics/coplogicidle.lua:971  _update_queued_tasks()                              
                                @mods/IRE                                           
                           AND                                                      
                          FIST  REBORN/lua/enemymanager.lua:62                      
                      update()  lib/managers/enemymanager.lua:51                    
                      update()  lib/setups/gamesetup.lua:723                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:557

**Comment by Siellenexia** [comment]
It looks like some incompatibility between this mod and The Fixes

**Comment by HugoZink** [comment]
This has been happening for a bit, I'm not entirely sure why this is happening.

Do you have a more complete crash.txt? The top line seems to be cut off, which just happens to be the most important line. If this keeps happening I can try to provide a debug mod which could help give a slightly clearer crashlog.

**Comment by ShelbyXIV** [comment]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main
Script stack:
            on_new_objective()  lib/units/enemies/cop/logics/coplogicbase.lua:412   
            on_new_objective()  lib/units/player_team/logics/teamailogicbase.lua:66  
            on_new_objective()  lib/units/player_team/logics/teamailogicidle.lua:478  
               set_objective()  lib/units/enemies/cop/copbrain.lua:265              
                    origfunc()  lib/managers/group_ai_states/groupaistatebase.lua:3324  
     objective_complete_clbk()  @mods/The                                           
                                Fixes/groupaistatebase.lua:7                        
                        clbk()                                                      
lib/units/enemies/cop/logics/coplogicidle.lua:971  _update_queued_tasks()                              
                                @mods/IRE                                           
                           AND                                                      
                          FIST  REBORN/lua/enemymanager.lua:62                      
                      update()  lib/managers/enemymanager.lua:51                    
                      update()  lib/setups/gamesetup.lua:723                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:557                   

-------------------------------

Here you go

**Comment by Bwamo** [comment]
Seems like the top part of the crash log is still missing

**Comment by ShelbyXIV** [comment]
Apologies, I'm not sure what you mean by "the top part." That's practically the entirety of the crash.txt without my PC's specifications

**Comment by Bwamo** [comment]
nevermind then
typically, crashes usually have the offending line followed by the scriptstack under it 
like in #20

**Comment by HugoZink** [comment]
> Application has crashed: access violation
That's the top part I was talking about. I know enough now, thanks for your report!

I'll be pushing an update with a "debug" option in the options. If this keeps happening, please enable it. Any logs after that should be more detailed.

@Bwamo true, but that's only if the crash happens inside Lua code. The lack of any such indication is actually information in itself, it means that the error happened inside a core C++ function/in-engine somewhere.

**Comment by ShelbyXIV** [comment]
No crashes while playing solo. But if the game crashes again while I'm hosting, I'll enable the option and provide the log.

**Comment by HugoZink** [comment]
I've made a lot of strides in preventing crashes on the clientside, they were all related to arrests. I'm going to assume this one was also fixed, as I haven't had a crash in ages.

There were so many crashes related to this feature that I said I'd never let that happen again. If I add another feature this size to the mod, it'll be locked behind the "beta" checkbox.
