### ISSUE TITLE
Sydch' Skill Overhaul (SSO) Compatibility issues

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#75]
_Yus, I'm still here_ (⌒_⌒;)
Just a question, not a request - since I wanted to try the Guardian until realised that I can't do it with [SSO](https://modworkshop.net/mod/24389) - 
What will happen with it from now on?
And if you will still support it - should I (we?) expect compatibility changes before SSO get an update, or later?

**Comment by HugoZink** [comment]
I wanted to test it without SSO first. SSO support will come very soon.

**Comment by MrVavlo** [comment]
Oh, I see.
Well, if anything needed from a SSO player - feel free to ask.


_At the same time, I'll check out the new assaults..._

**Comment by HugoZink** [comment]
SSO is now compatible.

**Comment by MrVavlo** [comment]
I think it's better to update this issue instead of creating the new one.

Last update of SSO partly broke the compatibility (who would expect, huh): some skills have old descriptions despite having new skills attached - for example, Marksman (which was moved to Tier 1) have removed movement penalty while aiming/increased zoom level in-game, while skill description have old bonuses aka "on paper" (increased zoom level and sniper rifles' reload speed/increased AR and SMG reload speed; which were true before the SSO update)

**Comment by HugoZink** [comment]
SSO has had a pretty big update so I'll probably have to redo most of it. Not a really big issue but something I'll have to look at. Thanks for the report!

**Comment by Olivefromspace** [comment]
Hi - my apologies if this isn't the correct place to post. I've been noticing some crashing issues with the latest version of SSO (latest as of a week ago). Seems to happen any time I crouch while jumping from a sprint. Checked the crash.txt - not an expert but the obvious culprit seems to be SSO, and I can't seem to think of any mod incompatibilities or options that would be causing this aside from that. This happens every time I do it - in case it's relevant I do have most of the Ghost/Enforcer skills related to movement kills and stamina.
[crash.txt](https://github.com/HugoZink/IreNFist/files/6354245/crash.txt)

**Comment by HugoZink** [comment]
Does this also happen without InF installed? SSO is currently known to be incompatible because it's a pretty big undertaking to update the support each time. I'm working on it, but slowly.

**Comment by HugoZink** [comment]
I haven't updated the SSO compatibility yet so there's probably lots of crashes, I'm working on it.

**Comment by Olivefromspace** [comment]
Ah, wondered if something like that might be the case. You might want to add a disclaimer to the MWS page, then - definitely wouldn't have filed an issue if there had been one (unless I'm completely blind and missed it somehow lol).

**Comment by HugoZink** [comment]
I'll add a disclaimer once I push the update later today, thanks.

Though I'm not sure if this is fixable, SSO seems to completely overwrite some functions (rather than PostHooking them), which is bound to give issues.

**Comment by Olivefromspace** [comment]
If there's anything I can do to help test I'd be happy to help! Otherwise, thank you for the quick responses and dedication. Love this mod a lot.

**Comment by HugoZink** [comment]
SSO compatibility is temporarily put on hold. The mod updates very fast and is hooked using BeardLib, which means I cannot reliably overwrite the mod's changes. Trying to work around this with delayed calls is quickly turning this codebase into a mess, so I should hold off on that for now.
