### ISSUE TITLE
CTD on arrest callback

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#77]
This happened twice today. It may or may not have something to do with clients not having InF installed.

    Application has crashed: C++ exception
    mods/IRE AND FIST REBORN/utils/coputils.lua:193: attempt to index local 'peer' (a nil value)
    SCRIPT STACK
    objective_complete_clbk() lib/managers/group_ai_states/groupaistatebesiege.lua:1810
    _on_destination_reached() lib/units/enemies/cop/logics/coplogictravel.lua:1467
    upd_advance() lib/units/enemies/cop/logics/coplogictravel.lua:264
    clbk() lib/units/enemies/cop/logics/coplogictravel.lua:194
    _execute_queued_task() @mods/IRE AND FIST REBORN/lua/enemymanager.lua:89
    _update_queued_tasks() @mods/IRE AND FIST REBORN/lua/enemymanager.lua:42
    update() lib/managers/enemymanager.lua:51
    update() lib/setups/gamesetup.lua:723
    update() lib/setups/networkgamesetup.lua:21
    core/lib/setups/coresetup.lua:557
    -------------------------------
    Callstack:
             payday2_win32_release  (???)     ???                                                 
             payday2_win32_release  (???)     ???                                                 
                               ???  (???)     ???                                                 
    -------------------------------
    Current thread: Main
    -------------------------------
    System information:
    	Application version : 1.96.909
    	CPU : Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    	DirectX : 11.0 
    	GPU : Intel(R) HD Graphics 4600 / igdumdim32.dll[10.18.14.4029]
    	Language : english
    	Memory :     12193MB 52KB
    	OS : 6.1.7600 () 0x300-0x1 (64 bits)
    	Physics : threaded
    	Renderer : DX9 threaded
    	Sound : IDT (Speakers / Headphones (IDT High Definition Audio CODEC))

**Comment by HugoZink** [comment]
That's... really odd. I'll take a look at that right now. Thanks!

**Comment by HugoZink** [comment]
Looks like I did have a nil check there, but a tiny mistake in operator precedence hid the bug completely. I have no idea why this didn't happen to me during my tests. I pushed out a fix.

Thanks for your report!
