### ISSUE TITLE
Trench Gun 1897 - all unique weapon parts have vanilla-like stats.

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#78]
![20201025002057_1](https://user-images.githubusercontent.com/34880333/97093839-0f074580-1658-11eb-8103-505040cf7c45.jpg)![20201025002447_1](https://user-images.githubusercontent.com/34880333/97093920-95238c00-1658-11eb-8896-7e368985b8b8.jpg)
Well, I would have skipped that, and seems like there's nothing in wpn_parts.lua for this shotgun, but there's "No-Man Barrel" and the bayonet giving damage boost (+100 and +25 respectively), which leads for pump shotgun with DB-tier damage...

**Comment by HugoZink** [comment]
Thanks, I'll take a look at this.

**Comment by HugoZink** [comment]
Fixed.
