### ISSUE TITLE
Headshotting a Taser with a heavy weapon does not trigger the voice lines

### ISSUE THREAD

**Issue by ShelbyXIV** [HugoZink/IreNFist#79]
Here's a preview:
https://youtu.be/_oA6aJvUCq4

**Comment by ShelbyXIV** [comment]
I presume it's from this mod because I don't recall if the passive ability was implemented for everyone and with every heavy weapon.

**Comment by HugoZink** [comment]
Thanks for the detailed report! I'll take a look.

**Comment by HugoZink** [comment]
Fixed.
