### ISSUE TITLE
Vanilla M. P. Attachment Stats

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#8]
Not sure if this is intended, but the attachments from the Vanilla Mod Pack still add stats that are not in line with IreNFist.
![20200801124800_1](https://user-images.githubusercontent.com/23544898/89106198-cee84c00-d3f5-11ea-84a8-8bfa83ac4f63.jpg)
![20200801125010_1](https://user-images.githubusercontent.com/23544898/89106199-cf80e280-d3f5-11ea-8d1e-fd5d4d60290a.jpg)

**Comment by Bwamo** [comment]
Resolved with commit [53d590e.](https://github.com/HugoZink/IreNFist/commit/53d590eed3897abfe5e27cf09e4c1a2c9b2c8c72)

**Comment by HugoZink** [comment]
Yep, coincidentally I've actually been going over this exact pack of weapons myself.

I'm currently uploading a fix for the ACAR-9 crashing on heist load.
