### ISSUE TITLE
Stone Cold attachment bug on Akimbo Jacket's Piece

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#81]
![payday2_win32_release_Or69PFqFyV](https://user-images.githubusercontent.com/71377805/97801785-c7914280-1c71-11eb-803e-a27395e8a4f0.png)

**Comment by HugoZink** [comment]
Lmao, I have no idea why that happens but I'll look into it.

I also just now realized that it doesn't really work well with the 80's calling mod. Might have to try and fix that.

**Comment by HugoZink** [comment]
Can you give a little more context on this bug? Is the weapon just floating in a specific part of the map, like that older bipod bug?

**Comment by ShelbyXIV** [comment]
It could be, to be honest. When I finish the reload, the position goes back into normal for a brief moment, then it's bugged again.

**Comment by HugoZink** [comment]
OHH wait, I just got it. This is on the akimbos, yes.

I can get that fixed pretty easily.

**Comment by HugoZink** [comment]
It's a little harder to fix but I'll get it done. I never actually set this lower receiver to work on the akimbo cobrays, so I'll have to manually make a new version specifically for the akimbos.

I'll get that done as soon as I make an "80's calling" version of the stone cold lower receiver.

**Comment by HugoZink** [comment]
Fixed. Took longer than I thought.
