### ISSUE TITLE
CTD on meleeing Matt (Safe House) or Santa (Stealing Xmas) again

### ISSUE THREAD

**Issue by millicentilottapede** [HugoZink/IreNFist#83]
woah deja vu

	Application has crashed: C++ exception
	mods/IRE AND FIST REBORN/lua/copdamage.lua:369: attempt to index a nil value
	SCRIPT STACK
	damage_melee() @mods/base/req/core/Hooks.lua:188
	_do_melee_damage() lib/units/beings/player/states/playerstandard.lua:2914
	_do_action_melee() @mods/IRE AND FIST REBORN/lua/playerstandard.lua:1730
	_start_action_melee() @mods/IRE AND FIST REBORN/lua/playerstandard.lua:1411
	old_cam() lib/units/beings/player/states/playerstandard.lua:2555
	_check_action_melee() @mods/IRE AND FIST REBORN/lua/playerstandard.lua:1462
	_update_check_actions() lib/units/beings/player/states/playerstandard.lua:936
	original() lib/units/beings/player/states/playerstandard.lua:435
	original() @mods/base/req/core/Hooks.lua:188
	update_original() @mods/base/req/core/Hooks.lua:265
	update() @mods/IRE AND FIST REBORN/lua/BurstFire.lua:350
	original() lib/units/beings/player/playermovement.lua:271
	@mods/base/req/core/Hooks.lua:265

I assume this has something to do with the melee headshot multiplier so I tried this by hitting the head and body on separate occasions, but it triggers the same error message regardless.

**Comment by HugoZink** [comment]
Huh that's weird, I thought I had unit tests to prevent this from happening. Sorry about that! I'll make sure to push a fix in the next release which will be soon.

**Comment by HugoZink** [comment]
Should be fixed.
