### ISSUE TITLE
[Suggestion] Add an option to make cops surrender only during assault breaks

### ISSUE THREAD

**Issue by ghost** [HugoZink/IreNFist#86]
I just played PD: TH again recently, and I was wondering if you can implement this to PD 2. This would give me another reason to keep civilians as hostages and get Stockholm Syndrome or something.

**Comment by HugoZink** [comment]
I think this is a great suggestion.

This was actually planned, sort of. I didn't want to make it impossible to dominate cops during assaults, but I did want to make it easier to dominate cops outside of assaults (and therefore harder during assaults).

I'm not sure if I can mess with the domination chances, but if I manage to, I'll make sure to add an option that makes cops never surrender in assaults. Thanks for your suggestion!

**Comment by artemisexe** [comment]
Okay, now that I think about it, this might be too much, considering the fact that some heists start with an endless assault. 

Decreasing the chance (further) during assaults may be better imo

**Comment by artemisexe** [comment]
An alternative suggestion would be applying this feature to non-endless heists or heists that start with endless assaults: Hoxton Breakout Day 1 until the garage and/or The Biker Heist Day 2.

**Comment by HugoZink** [comment]
Cops now surrender more easily outside of assaults. Implementing an option to make them *never* surrender in assaults is planned, but low priority.
