### ISSUE TITLE
Potential issue with Stockholm Syndrome

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#88]
It may be related to Stockholm Syndrome basic, judging from the crash log. However, I don't remember that I did call a civilian to help me, but the crash occurred as soon as I got downed, and I was mashing my shout button to help my teammate, so this one may narrow it down the issue.

Current thread: Main
Script stack:
_get_unit_intimidation_action()  @mods/IRE                                           
                                AND                                                 
                          FIST                                                      
REBORN/lua/playerbleedout.lua:130  call_civilian()                                     
                                @mods/IRE                                           
                           AND                                                      
                          FIST  REBORN/lua/playerbleedout.lua:11                    
      _check_action_interact()  lib/units/beings/player/states/playerbleedout.lua:271  
       _update_check_actions()  lib/units/beings/player/states/playerbleedout.lua:210  
                    original()  lib/units/beings/player/states/playerstandard.lua:435  
                    original()  @mods/base/req/core/Hooks.lua:188                   
             update_original()  @mods/base/req/core/Hooks.lua:265                   
                      update()  @mods/IRE                                           
                                AND                                                 
                          FIST                                                      
  REBORN/lua/BurstFire.lua:350  update()                                            
                                lib/units/beings/player/states/playerbleedout.lua:127  
                    original()                                                      
lib/units/beings/player/playermovement.lua:271  @mods/base/req/core/Hooks.lua:265

**Comment by HugoZink** [comment]
Probably an issue on my end somewhere. I'll try and fix it.

**Comment by HugoZink** [comment]
This should be fixed now. If it happens again please create another issue.
