### ISSUE TITLE
Sound bug on AMCAR

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#89]
The issue does not occur if I have Hawks_soundpack installed. However, the mod does cause other issues, particularly with bots' weapons and Skulldozers' LMGs. Other weapons work fine, I think. 

I'm not sure what causes this; I'm pretty sure this mod doesn't touch the sounds, but I also don't have other mods that touch the sounds of the weapons.

https://youtu.be/WYDu0wxlKY8

**Comment by HugoZink** [comment]
Does this happen without InF installed? I recently overrode the weapon `fire` function, if you have any BLT mods that alter the way weapon sounds work that aren't Autofire Soundfix 2, this might happen.

**Comment by artemisexe** [comment]
I don't think so, but I'm afraid I can't test it because I'll lose the weapons with custom/modded attachments. And I have other mods that alter them.

**Comment by HugoZink** [comment]
Cannot reproduce, it works on my end. Regardless of whether or not I have Hawk's Soundpack installed, and regardless of whether or not I have AFSF2 installed/enabled.

If you still want to try it without InF without losing your custom attachments, you can go to `Steam/userdata/(your steamIDv3)/218620` and backup the files there. These are your save files. You can back them up, test without InF, then put them back.
