### ISSUE TITLE
AK Pack Localization Issues

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#9]
Not sure if you intend to fix the rest of the strings like with the categories you fixed up, but some of the muzzle brakes and stocks have this issue. Some of the mods also have stat changes that don't match the stat modifying format of IreNFist as well.

![20200803175739_1](https://user-images.githubusercontent.com/23544898/89231429-4fa07700-d5b3-11ea-9371-95979087c851.jpg)
![20200803174252_1](https://user-images.githubusercontent.com/23544898/89231430-4fa07700-d5b3-11ea-9aac-ab41b41cb87d.jpg)

**Comment by HugoZink** [comment]
I could swear I fixed the AK pack, but apparently there's still some things left to fix.

Can you send me a link to this specific pack so I can make it compatible? They really oughta provide proper names themselves, but there's nothing stopping me from fixing it anyway.

**Comment by Bwamo** [comment]
You did partially fix AK Pack compatibility with [68fd8d5](https://github.com/HugoZink/IreNFist/commit/68fd8d53eb425bbe5cc9367fd40cb1a322f13cb3), but a few strings and attachments weren't done.
https://modworkshop.net/mod/26226

I personally don't intend to use this weapon pack as the sounds are functionally deafening and the AKs aren't really anything to write home about, but I'm sure there's some minority of the already tiny percentage of people that use IreNFist that will use this anyway.
