### ISSUE TITLE
Clarification on AMCAR's sound bug

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#90]
It is still odd because I don't have any other mods that hamper the weapons and their sounds. But then I notice that it happens on a modified AMCAR, not the stock one, so I tested it further without any modification, and the stock one worked fine. I removed the attachments from my modified AMCAR one-by-one to see which attachment causes it, and it's the heavy barrel modification.

**Comment by artemisexe** [comment]
Sorry that I forgot to mention this one.

**Comment by HugoZink** [comment]
Oh, so it's the heavy barrel? Thanks, that's worth looking into.

Actually now that you mention it, that's basically the AMR's "DMR kit" in vanilla. I'm willing to bet that the base game replaces the fire sound on it and that this breaks in vanilla. Thanks for the detailed report!

**Comment by artemisexe** [comment]
Happens on the modified MP5 as well. I'm not sure which attachment, though.

**Comment by HugoZink** [comment]
Probably the 10mm ammo. I'm still looking into this, but the new update kinda changed my priorities. Suddenly weapon firing sounds weren't working _at all_ anymore and I had to fix that first.

**Comment by HugoZink** [comment]
Fixed. I haven't been able to reproduce this on the MP5 even after trying out basically every attachment, but the AMCAR is good now.
