### ISSUE TITLE
Gun sounds loop indefinitely upon firing automatic weapon

### ISSUE THREAD

**Issue by XxFaZeDerpsxX** [HugoZink/IreNFist#92]
Whenever I shoot an automatic weapon, the firing sound loops indefinitely, even when another weapon is out.
I do have AFSF2 installed

**Comment by Bwamo** [comment]
following the release of U200, AFSF2 is now obsolete and is no longer required

**Comment by HugoZink** [comment]
Autofire sound fix isn't entirely _obsolete_, but it no longer works, and will probably cause issues like these. As a result, InF has also removed support for it. I strongly recommend removing AFSF.

Overkill didn't actually totally fix the fire sounds, they only fixed it for the first bullet. Try firing 3 rounds with the CZ-75, you will hear about 5 or 6 being fired. This problem gets worse with some other weapons as InF changes their fire rates.

Until AFSF2 is updated, you should remove it for now.

**Comment by Bwamo** [comment]
damn, I can't believe they half-assed a job

**Comment by HugoZink** [comment]
I implemented a fix for this issue in InF, so you shouldn't need AFSF anymore.

I have yet to make a toggle for this feature though.
