### ISSUE TITLE
Crash after shooting an explosive arrow

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#93]
Current thread: Main
Script stack:
                        func()  @mods/IRE                                           
                                AND                                                 
                          FIST                                                      
    REBORN/lua/raycast.lua:942  on_collision()                                      
                                @mods/base/req/core/Hooks.lua:182                   
               _on_collision()                                                      
lib/units/weapons/projectiles/arrowbase.lua:76  clbk_impact()                                       
                                lib/units/weapons/projectiles/projectilebase.lua:256  
                        func()                                                      
lib/units/weapons/projectiles/arrowbase.lua:95  body_collision_callback()                           
                                core/lib/units/coreunitdamage.lua:1537              
   lib/units/unitdamage.lua:92

**Comment by HugoZink** [comment]
I cannot reproduce this. Do you have more info? When does this happen? What are you shooting at?

**Comment by artemisexe** [comment]
It happened on Armored Crossroads. I was shooting at one of the Gensec guards. The guard may have collided with one of the trucks from the blast, and then the game crashed. However, I do think that it might be the game being wacky again.

**Comment by HugoZink** [comment]
I've tried to reproduce this in several heists but was unable to. If you have any more details, feel free to reopen the issue.
