### ISSUE TITLE
PDTH HUD and Vanilla Hud Plus compatibility

### ISSUE THREAD

**Issue by steam-test1** [HugoZink/IreNFist#94]
I fixed the PDTH HUD burst fire compatibility in the latest version and the breaching charges not showing with Vanilla HUD Plus
Also could IreNFist burst fire be disabled when burst fire is enabled with Vanilla HUD Plus

**Comment by HugoZink** [comment]
Sure, I'll do another round of testing and developing with PD:TH HUD and one with Vanilla HUD plus.

> Also could IreNFist burst fire be disabled when burst fire is enabled with Vanilla HUD Plus

Sure, but I think InF's burstfire is ever-so-slightly modified, so this may make some weapons (like the AN-94) behave a little differently.

I'll make sure to prevent InF's burstfire code from triggering if VHP is installed. It'll make its way into the next release. Thanks!

**Comment by HugoZink** [comment]
Fixed. The PD:TH compatibility part has been removed since it now works fine without that part.

The presence of Vanilla HUD Plus will now disable InF's burstfire.
