### ISSUE TITLE
Two bugs report

### ISSUE THREAD

**Issue by artemisexe** [HugoZink/IreNFist#95]
1. The sound of the first round/shot of the Buzzsaw Machine Gun is silent for some reason. I thought this was due to Hawks_soundpacks, but I've tested it with and without the mod, yet the problem still persists.

2. The extra magazines of the "OTs-14 Groza" custom weapon are improperly placed now.

**Comment by artemisexe** [comment]
![image](https://user-images.githubusercontent.com/71377805/99688325-3cf57380-2ab8-11eb-8060-fcdd47ab3c65.png)
![image](https://user-images.githubusercontent.com/71377805/99688360-454dae80-2ab8-11eb-86a8-45fb1a90bc68.png)
![image](https://user-images.githubusercontent.com/71377805/99688372-48e13580-2ab8-11eb-8a8b-6acb2ca16a85.png)
![Uploading image.png…]()
The last one is the stock magazine.

**Comment by HugoZink** [comment]
As for the Groza magazine issue and the sight, does the issue go away if you sell the weapon and get a new one?

The mod did indeed update (again), I'll see if I can fix it.

**Comment by HugoZink** [comment]
The floating sight will fix itself when you re-apply the sight, this is because it's on a rail now. That part isn't related to InF.

I just fixed the magazines, this fix will be in the next release. It'll be released shortly, I just have to fix PD:TH HUD Reborn and Vanilla HUD Plus compatibility real quick.

Thanks for your report!

**Comment by HugoZink** [comment]
The Groza is just a little bit more broken than I expected, so give me a bit to sift through this all.

**Comment by HugoZink** [comment]
Fixed.

**Comment by HugoZink** [comment]
I just now fixed the first MG42 bullet being silent as well, this was the fault of Overkill defining a single-fire sound for it that was silent.
