### ISSUE TITLE
Gangsters can also cuff you

### ISSUE THREAD

**Issue by ghost** [HugoZink/IreNFist#97]
![Screenshot (55)](https://user-images.githubusercontent.com/71377805/99957158-cc04d300-2db9-11eb-98e1-e610056a9118.png)
It is a bit hard to tell from this image, but it is the gangster's clothing. Also note that the first assault had not even started yet.

**Comment by HugoZink** [comment]
That's odd, the "is gangster" check must have been broken recently. I'll take a look, thanks!

**Comment by HugoZink** [comment]
Fixed (finally!)
