### ISSUE TITLE
Crash with Vanilla Hud Plus

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#98]
I had VHP's Burst Fire feature on during this crash.

Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/playertased.lua:172: attempt to call method '_in_burst_or_auto_mode' (a nil value)

SCRIPT STACK

_update_check_actions() lib/units/beings/player/states/playertased.lua:157
original() lib/units/beings/player/states/playerstandard.lua:435
original() @mods/base/req/core/Hooks.lua:188
update_original() @mods/base/req/core/Hooks.lua:265
update_original() @mods/VanillaHUD Plus/lua/BurstFire.lua:302
update() @mods/VanillaHUD Plus/lua/VanillaHUD.lua:852
update() lib/units/beings/player/states/playertased.lua:139
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265

**Comment by HugoZink** [comment]
Thanks, I'll take a look.

InF's burstfire code is now totally disabled with VHP, but I probably forgot to account for this in the playertased functions.

**Comment by HugoZink** [comment]
Sorry for the excessive delay, I'm about to push a fix for this.

**Comment by HugoZink** [comment]
Fixed.
